export { v0, createClient, type V0ClientConfig } from './sdk/v0'

// Export all schema types
export type {
  // Core entity types
  ChatDetail,
  ChatSummary,
  DeploymentDetail,
  DeploymentSummary,
  EnvironmentVariableDetailSchema,
  EnvironmentVariableSummarySchema,
  EnvironmentVariablesListSchema,
  FileDetail,
  FileSummary,
  HookDetail,
  HookEventDetail,
  HookSummary,
  IntegrationConnectionDetailSchema,
  IntegrationConnectionListSchema,
  IntegrationConnectionSummarySchema,
  IntegrationDetailSchema,
  IntegrationListSchema,
  IntegrationSummarySchema,
  MessageDetail,
  MessageSummary,
  MessageSummaryList,
  ProductDetailSchema,
  ProductListSchema,
  ProductSummarySchema,
  ProjectDetail,
  ProjectSummary,
  ScopeSummary,
  SearchResultItem,
  UserDetail,
  VercelProjectDetail,
  VercelProjectSummary,
  VersionDetail,
  VersionSummary,
  VersionSummaryList,

  // Request types
  ChatsCreateRequest,
  ChatsFavoriteRequest,
  ChatsForkRequest,
  ChatsInitRequest,
  ChatsSendMessageRequest,
  ChatsUpdateRequest,
  ChatsUpdateVersionRequest,
  DeploymentsCreateRequest,
  HooksCreateRequest,
  HooksUpdateRequest,
  IntegrationsVercelProjectsCreateRequest,
  ProjectsAssignRequest,
  ProjectsCreateEnvVarsRequest,
  ProjectsCreateRequest,
  ProjectsDeleteEnvVarsRequest,
  ProjectsUpdateEnvVarsRequest,
  ProjectsUpdateRequest,

  // Response types
  ChatsCreateResponse,
  ChatsDeleteResponse,
  ChatsFavoriteResponse,
  ChatsFindMessagesResponse,
  ChatsFindResponse,
  ChatsFindVersionsResponse,
  ChatsForkResponse,
  ChatsGetByIdResponse,
  ChatsGetMessageResponse,
  ChatsGetVersionResponse,
  ChatsInitResponse,
  ChatsResumeResponse,
  ChatsSendMessageResponse,
  ChatsUpdateResponse,
  ChatsUpdateVersionResponse,
  DeploymentsCreateResponse,
  DeploymentsDeleteResponse,
  DeploymentsFindErrorsResponse,
  DeploymentsFindLogsResponse,
  DeploymentsFindResponse,
  DeploymentsGetByIdResponse,
  HooksCreateResponse,
  HooksDeleteResponse,
  HooksFindResponse,
  HooksGetByIdResponse,
  HooksUpdateResponse,
  IntegrationsVercelProjectsCreateResponse,
  IntegrationsVercelProjectsFindResponse,
  ProjectsAssignResponse,
  ProjectsCreateEnvVarsResponse,
  ProjectsCreateResponse,
  ProjectsDeleteEnvVarsResponse,
  ProjectsFindEnvVarsResponse,
  ProjectsFindResponse,
  ProjectsGetByChatIdResponse,
  ProjectsGetByIdResponse,
  ProjectsGetEnvVarResponse,
  ProjectsUpdateEnvVarsResponse,
  ProjectsUpdateResponse,
  RateLimitsFindResponse,
  UserGetBillingResponse,
  UserGetPlanResponse,
  UserGetResponse,
  UserGetScopesResponse,
} from './sdk/v0'
